# fly.toml app configuration file generated for bloglist-cicd on 2024-04-09T22:21:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bloglist-cicd"
primary_region = "lhr"

[build]

[env]
  PORT = "3000" # add this where PORT matches the internal_port below

[processes]
  app = "node run start" # add this

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  strategy = "canary"  
