name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    env: 
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      TEST_MONGODB_URL: ${{ secrets.TEST_MONGODB_URL }}
      PORT: ${{ secrets.PORT }}
      SECRET: ${{ secrets.SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies
        run: npm install && cd frontend && npm install
      - name: Check style
        run: cd frontend && npm run lint
      - name: Test 
        run: npm run test
      - name: Build
        run: cd frontend && npm run build && cp -r dist ../
      - name: e2e Tests
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_BACKEND: http://localhost:3003/api
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3003
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}   
      - name: Build fail
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() && github.event_name == 'push' }}
        with: 
          severity: error
          text: Build failed
          details: commit broke ${{ github.event.commits.url }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}


  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message),'#skip') }}
        uses: anothrNick/github-tag-action@1.67.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch 
      - name: New version success
        if: ${{ success() && github.event_name == 'push' }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          text: A new version of pokedex deployed https://full-stack-open-pokedex-cicd-2024.fly.dev
          details: Healthcheck successful 
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}